// <auto-generated />
namespace Zeus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2310 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2310));
        
        string IMigrationMetadata.Id
        {
            get { return "202006142210291_2310"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
