// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _17393011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17393011));
        
        string IMigrationMetadata.Id
        {
            get { return "202011301739420_17393011"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
