// <auto-generated />
namespace Zeus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1840 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1840));
        
        string IMigrationMetadata.Id
        {
            get { return "202010111740180_1840"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
