// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sprint20210806 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sprint20210806));
        
        string IMigrationMetadata.Id
        {
            get { return "202112031912066_Sprint2021.08.06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
