// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SprintJan20215 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SprintJan20215));
        
        string IMigrationMetadata.Id
        {
            get { return "202101230542088_SprintJan2021-5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
