// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sprint20210902 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sprint20210902));
        
        string IMigrationMetadata.Id
        {
            get { return "202112211704087_Sprint2021.09.02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
