// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SprintFeb20212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SprintFeb20212));
        
        string IMigrationMetadata.Id
        {
            get { return "202102071101205_SprintFeb2021-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
