// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SprintDec2020HF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SprintDec2020HF));
        
        string IMigrationMetadata.Id
        {
            get { return "202101062044142_SprintDec2020HF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
