// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SprintFeb20211 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SprintFeb20211));
        
        string IMigrationMetadata.Id
        {
            get { return "202102060804009_SprintFeb2021-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
