// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sprint20221005 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sprint20221005));
        
        string IMigrationMetadata.Id
        {
            get { return "202201061113234_Sprint2022.10.05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
