// <auto-generated />
namespace Dertrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sprint20220204 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sprint20220204));
        
        string IMigrationMetadata.Id
        {
            get { return "202202220634561_Sprint2022.02.04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
